print("\n=== Lista de Libros ===")
print(100*"=")
print("+----+--------------------+--------------------+------+--------------------+------------+----------+")
print("| ID | Título             | Autor              | Año  | Editorial          | ISBN       | Stock    |")
print("+----+--------------------+--------------------+------+--------------------+------------+----------+")
print(100*"=")
print(100*"=")
print(100*"-")
print("|                              MENÚ DE OPCIONES DISTRIBUIDORA LIBROS                               |")
print(100*"-")
print("|                                                                                                  |")
print("|                                    1 - REGISTRAR LIBRO                                           |")
print("|                                    2 - ACTUALIZAR LIBRO                                          |")
print("|                                    3 - ELIMINAR LIBRO                                            |")
print("|                                    4 - BUSCAR LIBRO                                              |")
print("|                                    5 - LISTAR LIBROS                                             |")
print("|                                    6 - REPORTE DE LIBROS CON BAJO STOCK                          |")
print("|                                    0 - SALIR DE SISTEMA                                          |")
print("|                                                                                                  |")
print(100*"-")
